sonar.projectKey=jackson-json-java
sonar.projectName=jackson-json-java
sonar.projectVersion=1.0
sonar.login=admin

sonar.sources=jackson-json-java/src
sonar.java.binaries=jackson-json-java/target/classes

sonar.sourceEncoding=UTF-8
